spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      path: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://database.coor5hp3r5a0.ap-northeast-2.rds.amazonaws.com:3306/laundry-project
    password: 3AHKStMaHM
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    encoding:
      charset: UTF-8
    context-path: /
